In [53]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression   

In [3]:
data=pd.read_csv("startups.csv")
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.groupby("State").sum("Profit")

R&D Spend  Administration  Marketing Spend      Profit
State                                                              
California  1099180.46      2052690.62       3103195.80  1766387.98
Florida     1291584.26      1948302.36       3957176.82  1900384.39
New York    1295316.06      2066239.00       3490882.27  1933859.59

In [5]:
dummies=pd.get_dummies(data.State)
dummies

California  Florida  New York
0            0        0         1
1            1        0         0
2            0        1         0
3            0        0         1
4            0        1         0
5            0        0         1
6            1        0         0
7            0        1         0
8            0        0         1
9            1        0         0
10           0        1         0
11           1        0         0
12           0        1         0
13           1        0         0
14           0        1         0
15           0        0         1
16           1        0         0
17           0        0         1
18           0        1         0
19           0        0         1
20           1        0         0
21           0        0         1
22           0        1         0
23           0        1         0
24           0        0         1
25           1        0         0
26           0        1         0
27           0        0         1
28           0        1         0
29           0        0         1
30           0        1         0
31           0        0         1
32           1        0         0
33           0        1         0
34           1        0         0
35           0        0         1
36           0        1         0
37           1        0         0
38           0        0         1
39           1        0         0
40           1        0         0
41           0        1         0
42           1        0         0
43           0        0         1
44           1        0         0
45           0        0         1
46           0        1         0
47           1        0         0
48           0        0         1
49           1        0         0

In [6]:
merged=pd.concat([data,dummies],axis='columns')
merged

R&D Spend  Administration  Marketing Spend       State     Profit  \
0   165349.20       136897.80        471784.10    New York  192261.83   
1   162597.70       151377.59        443898.53  California  191792.06   
2   153441.51       101145.55        407934.54     Florida  191050.39   
3   144372.41       118671.85        383199.62    New York  182901.99   
4   142107.34        91391.77        366168.42     Florida  166187.94   
5   131876.90        99814.71        362861.36    New York  156991.12   
6   134615.46       147198.87        127716.82  California  156122.51   
7   130298.13       145530.06        323876.68     Florida  155752.60   
8   120542.52       148718.95        311613.29    New York  152211.77   
9   123334.88       108679.17        304981.62  California  149759.96   
10  101913.08       110594.11        229160.95     Florida  146121.95   
11  100671.96        91790.61        249744.55  California  144259.40   
12   93863.75       127320.38        249839.44     Florida  141585.52   
13   91992.39       135495.07        252664.93  California  134307.35   
14  119943.24       156547.42        256512.92     Florida  132602.65   
15  114523.61       122616.84        261776.23    New York  129917.04   
16   78013.11       121597.55        264346.06  California  126992.93   
17   94657.16       145077.58        282574.31    New York  125370.37   
18   91749.16       114175.79        294919.57     Florida  124266.90   
19   86419.70       153514.11             0.00    New York  122776.86   
20   76253.86       113867.30        298664.47  California  118474.03   
21   78389.47       153773.43        299737.29    New York  111313.02   
22   73994.56       122782.75        303319.26     Florida  110352.25   
23   67532.53       105751.03        304768.73     Florida  108733.99   
24   77044.01        99281.34        140574.81    New York  108552.04   
25   64664.71       139553.16        137962.62  California  107404.34   
26   75328.87       144135.98        134050.07     Florida  105733.54   
27   72107.60       127864.55        353183.81    New York  105008.31   
28   66051.52       182645.56        118148.20     Florida  103282.38   
29   65605.48       153032.06        107138.38    New York  101004.64   
30   61994.48       115641.28         91131.24     Florida   99937.59   
31   61136.38       152701.92         88218.23    New York   97483.56   
32   63408.86       129219.61         46085.25  California   97427.84   
33   55493.95       103057.49        214634.81     Florida   96778.92   
34   46426.07       157693.92        210797.67  California   96712.80   
35   46014.02        85047.44        205517.64    New York   96479.51   
36   28663.76       127056.21        201126.82     Florida   90708.19   
37   44069.95        51283.14        197029.42  California   89949.14   
38   20229.59        65947.93        185265.10    New York   81229.06   
39   38558.51        82982.09        174999.30  California   81005.76   
40   28754.33       118546.05        172795.67  California   78239.91   
41   27892.92        84710.77        164470.71     Florida   77798.83   
42   23640.93        96189.63        148001.11  California   71498.49   
43   15505.73       127382.30         35534.17    New York   69758.98   
44   22177.74       154806.14         28334.72  California   65200.33   
45    1000.23       124153.04          1903.93    New York   64926.08   
46    1315.46       115816.21        297114.46     Florida   49490.75   
47       0.00       135426.92             0.00  California   42559.73   
48     542.05        51743.15             0.00    New York   35673.41   
49       0.00       116983.80         45173.06  California   14681.40   

    California  Florida  New York  
0            0        0         1  
1            1        0         0  
2            0        1         0  
3            0        0         1  
4            0        1         0  
5            0        0         1  
6            1        0     

In [7]:
final=merged.copy()
final.head()

R&D Spend  Administration  Marketing Spend       State     Profit  \
0  165349.20       136897.80        471784.10    New York  192261.83   
1  162597.70       151377.59        443898.53  California  191792.06   
2  153441.51       101145.55        407934.54     Florida  191050.39   
3  144372.41       118671.85        383199.62    New York  182901.99   
4  142107.34        91391.77        366168.42     Florida  166187.94   

   California  Florida  New York  
0           0        0         1  
1           1        0         0  
2           0        1         0  
3           0        0         1  
4           0        1         0

In [8]:
final.drop(axis=1,columns=["State","New York"],inplace=True)


In [9]:
final.head()

R&D Spend  Administration  Marketing Spend     Profit  California  Florida
0  165349.20       136897.80        471784.10  192261.83           0        0
1  162597.70       151377.59        443898.53  191792.06           1        0
2  153441.51       101145.55        407934.54  191050.39           0        1
3  144372.41       118671.85        383199.62  182901.99           0        0
4  142107.34        91391.77        366168.42  166187.94           0        1

In [10]:
x=final[["R&D Spend","Administration","Marketing Spend","California","Florida"]].values
y=final[["Profit"]].values

In [11]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0)
test_y

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [12]:
MLR=LinearRegression()
MLR.fit(train_x,train_y)


LinearRegression()

In [13]:
pred_y=MLR.predict(test_x)
print([pred_y])
print([test_y])

[array([[103015.20159776],
       [132582.27760831],
       [132447.73845184],
       [ 71976.09851266],
       [178537.4822107 ],
       [116161.24230157],
       [ 67851.69209689],
       [ 98791.73374679],
       [113969.43533008],
       [167921.06569569]])]
[array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])]


In [14]:
MLR.predict([[180000,151377.59,443898.53,1,0]])

array([[203007.39009701]])

In [15]:
MLR.intercept_

array([43253.53667068])

In [16]:
MLR.coef_

array([[ 7.73467193e-01,  3.28845975e-02,  3.66100259e-02,
        -6.99369053e+02, -1.65865321e+03]])

In [84]:
a1=MLR.score(train_x,train_y)
b1=MLR.score(test_x,test_y)
a1-b1

0.015477915419860988

# backward elimination

In [21]:
import statsmodels.api as sm

In [24]:
x=np.append(arr=np.ones((50,1)).astype(int),values=x,axis=1)

In [25]:
x

array([[1.0000000e+00, 1.6534920e+05, 1.3689780e+05, 4.7178410e+05,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.6259770e+05, 1.5137759e+05, 4.4389853e+05,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.5344151e+05, 1.0114555e+05, 4.0793454e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.4437241e+05, 1.1867185e+05, 3.8319962e+05,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.4210734e+05, 9.1391770e+04, 3.6616842e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.3187690e+05, 9.9814710e+04, 3.6286136e+05,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.3461546e+05, 1.4719887e+05, 1.2771682e+05,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.3029813e+05, 1.4553006e+05, 3.2387668e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.2054252e+05, 1.4871895e+05, 3.1161329e+05,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.2333488e+05,

In [27]:
x_opt=x[:,[0,1,2,3,4,5]]

In [28]:
reg_OLS=sm.OLS(endog=y,exog=x_opt).fit()

In [29]:
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 17 Jan 2021   Prob (F-statistic):           1.34e-27
Time:                        12:25:33   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.008e+04   6952.587      7.204      0.000    3.61e+04    6.41e+04
x1             0.8060      0.046     17.369      0.000       0.712       0.900
x2            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x3             0.0270      0.017      1.574      0.123      -0.008       0.062
x4            41.8870   3256.039      0.013      0.990   -6520.229    6604.003
x5           240.6758   3338.857      0.072      0.943   -6488.349    6969.701
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.47e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [30]:
x_opt=x[:,[0,1,3,4,5]]
reg_OLS=sm.OLS(endog=y,exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     215.8
Date:                Sun, 17 Jan 2021   Prob (F-statistic):           9.72e-29
Time:                        12:30:20   Log-Likelihood:                -525.53
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1071.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.694e+04   3342.591     14.043      0.000    4.02e+04    5.37e+04
x1             0.7967      0.042     18.771      0.000       0.711       0.882
x2             0.0298      0.016      1.842      0.072      -0.003       0.062
x3            19.5234   3229.138      0.006      0.995   -6484.294    6523.340
x4           160.3104   3307.973      0.048      0.962   -6502.289    6822.910
==============================================================================
Omnibus:                       14.640   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.037
Skew:                          -0.938   Prob(JB):                     2.70e-05
Kurtosis:                       5.565   Cond. No.                     8.90e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.9e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [31]:
x_opt=x[:,[0,1,3,5]]
reg_OLS=sm.OLS(endog=y,exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.947
Method:                 Least Squares   F-statistic:                     294.1
Date:                Sun, 17 Jan 2021   Prob (F-statistic):           5.19e-30
Time:                        12:30:53   Log-Likelihood:                -525.53
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1067.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.695e+04   2761.499     17.002      0.000    4.14e+04    5.25e+04
x1             0.7967      0.042     19.024      0.000       0.712       0.881
x2             0.0298      0.016      1.863      0.069      -0.002       0.062
x3           150.7580   2874.516      0.052      0.958   -5635.342    5936.858
==============================================================================
Omnibus:                       14.628   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               20.992
Skew:                          -0.938   Prob(JB):                     2.76e-05
Kurtosis:                       5.560   Cond. No.                     5.99e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.99e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [32]:
x_opt=x[:,[0,1,3]]
reg_OLS=sm.OLS(endog=y,exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sun, 17 Jan 2021   Prob (F-statistic):           2.16e-31
Time:                        12:31:19   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
x_opt=x[:,[0,1]]
reg_OLS=sm.OLS(endog=y,exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sun, 17 Jan 2021   Prob (F-statistic):           3.50e-32
Time:                        12:32:46   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

As we can see in the above output image, only two variables are left. So only the R&D independent variable is a significant variable for the prediction. So we can now predict efficiently using this variable

In [51]:
data_set= pd.read_csv('startups.csv')  
  
data_set=data_set.iloc[:,[0,4]]
data_set.head()


R&D Spend     Profit
0  165349.20  192261.83
1  162597.70  191792.06
2  153441.51  191050.39
3  144372.41  182901.99
4  142107.34  166187.94

In [76]:
reg3=LinearRegression()
x=data_set.iloc[:,0].values.reshape(-1,1)
y=data_set.iloc[:,1].values.reshape(-1,1)
training_x,testing_x,training_y,testing_y=train_test_split(x,y,test_size=0.3,random_state=0)
reg3.fit(training_x,training_y)

LinearRegression()

In [77]:
reg3.predict(testing_x)

array([[104347.29054818],
       [134059.15325094],
       [135124.30398379],
       [ 71598.91750239],
       [179346.89726824],
       [109544.72355241],
       [ 65022.1146424 ],
       [100129.03206143],
       [111164.14538661],
       [169619.71578557],
       [ 95286.60066917],
       [ 87150.76014861],
       [112309.27339546],
       [ 87504.38861279],
       [126401.4513695 ]])

In [78]:
print(testing_y)

[[103282.38]
 [144259.4 ]
 [146121.95]
 [ 77798.83]
 [191050.39]
 [105008.31]
 [ 81229.06]
 [ 97483.56]
 [110352.25]
 [166187.94]
 [ 96778.92]
 [ 96479.51]
 [105733.54]
 [ 96712.8 ]
 [124266.9 ]]


In [90]:
a=reg3.score(training_x,training_y)
b=reg3.score(testing_x,testing_y)
print("before backward elimination=",a1-b1)
print("after backward elimination",a-b)

before backward elimination= 0.015477915419860988
after backward elimination 0.011604748554385647
